# Generated by Django 4.2.6 on 2023-10-07 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('country', models.TextField(verbose_name='страна')),
                ('city', models.TextField(verbose_name='город')),
                ('street', models.TextField(verbose_name='улица')),
                ('house', models.TextField(verbose_name='дом')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.link', verbose_name='цепь звена')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакты',
            },
        ),
    ]
