# Generated by Django 4.2.6 on 2023-10-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_link_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название звена'),
        ),
    ]
