# Generated by Django 4.2.6 on 2023-10-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_link_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='debt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True, verbose_name='Задолженность перед поставщиком'),
        ),
    ]
